@extends('layouts.base')

@section('title', 'Two-Factor Authentication — Zoom Pool Manager')

@section('content')
<div class="max-w-md mx-auto my-8" x-data="{ useRecovery: false }">
    <div class="bg-white dark:bg-slate-800 shadow-xl rounded-2xl border border-slate-200 dark:border-slate-700 overflow-hidden">
        <div class="px-8 pt-8 pb-6 text-center">
            <div class="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-sky-100 dark:bg-sky-900/50 text-sky-600 dark:text-sky-400 mb-4">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"/>
                </svg>
            </div>
            <h1 class="text-2xl font-bold text-slate-900 dark:text-white">Two-Factor Authentication</h1>
            <p class="text-sm text-slate-500 dark:text-slate-400 mt-1" x-show="!useRecovery">
                Enter the 6-digit verification code generated by your authenticator app.
            </p>
            <p class="text-sm text-slate-500 dark:text-slate-400 mt-1" x-show="useRecovery" x-cloak>
                Enter one of your 10-character emergency recovery codes.
            </p>
        </div>

        <div class="px-8 pb-8 space-y-6">
            @if ($errors->any())
                <div class="p-4 bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-800 rounded-xl text-sm text-rose-700 dark:text-rose-400">
                    <ul class="list-disc list-inside space-y-1">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('auth.totp.post') }}" method="POST" class="space-y-4">
                @csrf
                <div x-show="!useRecovery">
                    <label for="code_totp" class="block text-sm font-medium text-slate-700 dark:text-slate-300">Authenticator Code</label>
                    <input type="text" inputmode="numeric" pattern="[0-9]*" maxlength="6" name="code" id="code_totp" placeholder="000000" autofocus
                           :disabled="useRecovery"
                           class="mt-1 block w-full px-3.5 py-3 tracking-widest text-center text-2xl font-mono bg-slate-50 dark:bg-slate-900/60 border border-slate-300 dark:border-slate-700 rounded-xl text-slate-900 dark:text-white focus:ring-2 focus:ring-sky-500 focus:outline-none">
                </div>

                <div x-show="useRecovery" x-cloak>
                    <label for="code_recovery" class="block text-sm font-medium text-slate-700 dark:text-slate-300">Emergency Recovery Code</label>
                    <input type="text" name="code" id="code_recovery" placeholder="XXXXX-XXXXX"
                           :disabled="!useRecovery" disabled
                           class="mt-1 block w-full px-3.5 py-3 tracking-widest text-center text-lg font-mono uppercase bg-slate-50 dark:bg-slate-900/60 border border-slate-300 dark:border-slate-700 rounded-xl text-slate-900 dark:text-white focus:ring-2 focus:ring-sky-500 focus:outline-none">
                </div>

                <button type="submit"
                        class="w-full py-2.5 px-4 bg-sky-600 hover:bg-sky-700 text-white font-medium rounded-xl shadow-sm transition">
                    Verify & Continue
                </button>
            </form>

            <div class="pt-4 text-center border-t border-slate-100 dark:border-slate-700/60">
                <button type="button" @click="useRecovery = !useRecovery" class="text-xs text-sky-600 dark:text-sky-400 hover:underline">
                    <span x-show="!useRecovery">Lost your device? Use an emergency recovery code</span>
                    <span x-show="useRecovery" x-cloak>Use authenticator code instead</span>
                </button>
            </div>
        </div>
    </div>
</div>
@endsection
